<template><div><div class="page-title"><div><h1>调班与替班申请</h1><p>申请先由替班人确认，同意后再交主管审批；双方都同意后系统才会交换双方排班。</p></div></div><el-card><el-table :data="rows"><el-table-column prop="id" label="#" width="70"/><el-table-column label="申请人"><template #default="scope">{{scope.row.applicant?.name}}</template></el-table-column><el-table-column label="替班人"><template #default="scope">{{scope.row.substitute?.name}}</template></el-table-column><el-table-column prop="reason" label="调班原因"/><el-table-column label="状态" width="120"><template #default="scope"><el-tag :type="statusType(scope.row.status)">{{statusText(scope.row.status)}}</el-tag></template></el-table-column><el-table-column label="当前待处理" width="180"><template #default="scope">{{waitingText(scope.row)}}</template></el-table-column><el-table-column label="操作" width="190"><template #default="scope"><template v-if="canConfirm(scope.row)"><el-button size="small" type="success" :disabled="busy" @click="confirm(scope.row,true)">同意换班</el-button><el-button size="small" :disabled="busy" @click="confirm(scope.row,false)">拒绝换班</el-button></template><template v-else-if="canReview(scope.row)"><el-button size="small" type="success" :disabled="busy" @click="review(scope.row,true)">同意</el-button><el-button size="small" :disabled="busy" @click="review(scope.row,false)">驳回</el-button></template><span v-else>—</span></template></el-table-column></el-table></el-card></div></template>
<script setup lang="ts">
import {onMounted, ref} from 'vue'; import {ElMessage} from 'element-plus'; import api from '../api/http'; import {auth} from '../stores/auth'
const rows=ref<any[]>([]); const busy=ref(false)
const statusMap:Record<string,{text:string;type:string}>={awaiting_substitute:{text:'待替班人确认',type:'warning'},pending:{text:'待主管审批',type:'warning'},approved:{text:'已完成',type:'success'},rejected:{text:'主管已驳回',type:'danger'},declined:{text:'替班人已拒绝',type:'info'}}
function statusText(s:string){return statusMap[s]?.text||s}
function statusType(s:string){return (statusMap[s]?.type||'info') as any}
function waitingText(row:any){if(row.status==='awaiting_substitute')return `等待替班人 ${row.substitute?.name||''} 确认`;if(row.status==='pending')return '等待主管审批';return '已结束'}
function canConfirm(row:any){return row.status==='awaiting_substitute'&&row.substitute_id===auth.staffId}
function canReview(row:any){return row.status==='pending'&&(auth.role==='admin'||auth.role==='supervisor')}
async function load(){rows.value=await api.get('/shift-requests')}
async function confirm(row:any,accepted:boolean){busy.value=true;try{await api.put(`/shift-requests/${row.id}/confirm`,{accepted});ElMessage.success(accepted?'已同意换班，等待主管审批':'已拒绝换班，申请结束');await load()}catch(error:any){ElMessage.error(error.message)}finally{busy.value=false}}
async function review(row:any,approved:boolean){busy.value=true;try{await api.put(`/shift-requests/${row.id}/review`,{approved});ElMessage.success('审批已完成');await load()}catch(error:any){ElMessage.error(error.message)}finally{busy.value=false}}
onMounted(load)
</script>
